# ============================================================
# RESQ-FLOW
# PRIORITY ENGINE
# ============================================================
#
# Uses the urgency score generated by the AI.
#
# AI Message Analysis
#        ↓
#   Urgency Score
#        ↓
#   Priority Level
#
# No additional scoring is performed here.
#
# ============================================================


def calculate_priority(urgency_score: int):
    """
    Convert the AI urgency score into a priority level.
    """

    if urgency_score >= 75:
        priority_level = "CRITICAL"

    elif urgency_score >= 50:
        priority_level = "HIGH"

    elif urgency_score >= 25:
        priority_level = "MODERATE"

    elif urgency_score > 0:
        priority_level = "LOW"

    else:
        priority_level = "NONE"

    return {
        "urgency_score": urgency_score,
        "priority_level": priority_level
    }